Fiddling around with trust

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -2,10 +2,11 @@
 
 set -euo pipefail
 
-keys=("25A33431D0C867CF69199E24B1D8325468344D5F")
-config="https://github.com/lordvadr/lemmy-server-config.git"
+sshkeys="https://github.com/lordvadr/futurology-ssh-keys.git"
+gpgkeys="https://github.com/lordvadr/futurology-gpg-keys.git"
+config="https://github.com/lordvadr/futurology-lemmy-server-config.git"
 branch="main"
-workdir="server-config"
+workdir="workdir"
 
 die() {
 	>&2 echo "FATAL: ${@:-UNKNOWN ERROR}"
@@ -17,8 +18,26 @@ cleanup() {
 	[ "${rv}" == "0" ] || { >&2 echo "FATAL FATAL FATAL FATAL !!!!!! SCRIPT DID NOT EXIT CLEANLY"; }
 }
 
-trustkey() {
-	gpg --keyserver keys.openpgp.org --recv-keys "${1}" && echo "${1}:6:" | gpg --import-ownertrust
+last_signed_commit() {
+	pushd "${1}" || die "Could not cd into \"${1}\"."
+
+	git checkout "${branch}" || die "Could not checkout \"${branch}\" branch."
+	COMMIT=""
+
+	for c in $(git log --pretty=format:"%H"); do
+		if git verify-commit "${c}"; then
+			COMMIT="${c}"
+			git checkout "${c}"
+			break
+		else
+			COMMIT=""
+		fi
+	done
+
+	[ -n "${COMMIT}" ] || die "No signed commit found."
+
+	echo "Most recent signed commit for "${1}" is \"${COMMIT}\"."
+	popd
 }
 
 trap cleanup EXIT
@@ -27,34 +46,36 @@ cd /root || die "Could not change working directory to /root"
 
 sudo dnf -y --allowerasing install dirmngr git || die "Could not install git and other tools."
 
-for key in "${keys[@]}"; do
-	trustkey "${key}" || die "Could not import key/set trust for keyid \"${key}\"."
-done
+gpg --import << EOF
+-----BEGIN PGP PUBLIC KEY BLOCK-----
+
+mDMEZJMXzRYJKwYBBAHaRw8BAQdAxAkZQFi5MkN0Z9mIpicIwwYx0IYe7G+B0vSG
+TWIDPhq0JWxvcmR2YWRyIDxsb3JkdmFkckBmdXR1cm9sb2d5LnNvY2lhbD6ImQQT
+FgoAQRYhBCWjNDHQyGfPaRmeJLHYMlRoNE1fBQJkkxfNAhsBBQkDwmcABQsJCAcC
+AiICBhUKCQgLAgQWAgMBAh4HAheAAAoJELHYMlRoNE1fd1sA+gM4ORfzaYq3pdjQ
+Liqje/CfO1N23OmfslVPGUoO5YGEAPsEOr2nFF2RAx8ojJU4GO7dD8vJU7cDdzuL
+TvCsmAEaBw==
+=HV9t
+-----END PGP PUBLIC KEY BLOCK-----
+EOF
+
+echo "25A33431D0C867CF69199E24B1D8325468344D5F:6:" | gpg --import-ownertrust
+
+gpg --keyserver keys.openpgp.org --refresh-keys
 
 [ ! -d "${workdir}" ] && [ ! -e "${workdir}" ] || rm -rf "${workdir}" || die "Could not remove stale workdir \"${workdir}\"."
 
-git clone "${config}" "${workdir}" || die "Could not clone configuration repository."
+mkdir -p "${workdir}" && pushd "${workdir}" || die "Could not create and cd into working directory \"${workdir}\"."
 
-pushd "${workdir}" || die "Could not cd into working directory \"${workdir}\"."
+git clone "${sshkeys}" ssh-keys
+git clone "${gpgkeys}" gpg-keys
+git clone "${config}" config
 
-git checkout "${branch}" || die "Could not checkout \"${branch}\" branch."
+last_signed_commit ssh-keys
+last_signed_commit gpg-keys
+last_signed_commit config
 
-COMMIT=""
-
-for c in $(git log --pretty=format:"%H"); do
-	if git verify-commit "${c}"; then
-		COMMIT="${c}"
-		git checkout "${c}"
-		break
-	else
-		COMMIT=""
-	fi
-done
-
-[ -n "${COMMIT}" ] || die "No signed commit found."
-
-echo "Most recent signed commit is \"${COMMIT}\"."
-
+pushd config
 [ -e "setup.sh" ] || die "No \"setup.sh\" script to launch."
 
 [ -x "setup.sh" ] || die "\"setup.sh\" is not executabel."
